"""empty message

Revision ID: 87ecc70f7289
Revises: eeec03654cf9
Create Date: 2024-06-03 09:15:29.944925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ecc70f7289'
down_revision = 'eeec03654cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_issues', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
