"""empty message

Revision ID: ebbe668a57a5
Revises: 1084c9daeb40
Create Date: 2024-05-31 16:36:35.840609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebbe668a57a5'
down_revision = '1084c9daeb40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reader', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fname', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('lname', sa.String(length=100), nullable=True))
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reader', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('lname')
        batch_op.drop_column('fname')

    # ### end Alembic commands ###
